-- Set REPLICA IDENTITY FULL for all tables to support CDC (Change Data Capture)
ALTER TABLE "User" REPLICA IDENTITY FULL;
ALTER TABLE "Trip" REPLICA IDENTITY FULL;
ALTER TABLE "Day" REPLICA IDENTITY FULL;
ALTER TABLE "TripMember" REPLICA IDENTITY FULL;
ALTER TABLE "Activity" REPLICA IDENTITY FULL;
ALTER TABLE "Expense" REPLICA IDENTITY FULL;
ALTER TABLE "ExpenseParticipant" REPLICA IDENTITY FULL;
ALTER TABLE "SocialAccount" REPLICA IDENTITY FULL;
ALTER TABLE "PaymentSettlement" REPLICA IDENTITY FULL;
ALTER TABLE "PaymentTransaction" REPLICA IDENTITY FULL;
ALTER TABLE "Device" REPLICA IDENTITY FULL;
ALTER TABLE "Notification" REPLICA IDENTITY FULL;
ALTER TABLE "Province" REPLICA IDENTITY FULL;
ALTER TABLE "TripTemplate" REPLICA IDENTITY FULL;
ALTER TABLE "TripTemplateDay" REPLICA IDENTITY FULL;
ALTER TABLE "TripTemplateActivity" REPLICA IDENTITY FULL;
ALTER TABLE "Template" REPLICA IDENTITY FULL;
ALTER TABLE "Otp" REPLICA IDENTITY FULL;
ALTER TABLE "Rating" REPLICA IDENTITY FULL;
ALTER TABLE "SystemConfig" REPLICA IDENTITY FULL;
ALTER TABLE "UserAiUsage" REPLICA IDENTITY FULL;
-- Also handle implicit join tables if any
ALTER TABLE "_UserWishlist" REPLICA IDENTITY FULL;