version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs_app_dev
    working_dir: /usr/src/app
    ports:
      - "3001:3000"
    env_file:
      - .env.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./:/usr/src/app
      - node_modules_dev:/usr/src/app/node_modules
    command: npm run start:dev
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  node_modules_dev: