FROM node:18-slim

WORKDIR /usr/src/app

COPY package*.json ./

RUN apt-get update && apt-get install -y openssl curl && npm install

COPY . .

RUN npx prisma generate
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]